# https://starship.rs/config/#character

add_newline=true

[aws]
disabled=true

[battery]
disabled=true

[character]
success_symbol="[->](green)"
error_symbol="[-X](red)"

[cmake]
disabled=true

[cobol]
disabled=true

[cmd_duration]
min_time=1_000

[conda]
disabled=true

[crystal]
disabled=true

[dart]
disabled=true

[deno]
disabled=true

[directory]
truncation_symbol=""
home_symbol="$HOME"
format="[$path]($style)[$read_only]($read_only_style) "

[docker_context]
disabled=true

[dotnet]
disabled=true

[elixir]
disabled=true

[elm]
disabled=true

[env_var]
disabled=true

[erlang]
disabled=true

[fill]
disabled=true

[gcloud]
disabled=true

[git_state]
disabled=true

[git_metrics]
disabled=true

[golang]
disabled=true

[helm]
disabled=true

[hostname]
disabled=true

[java]
disabled=true

[jobs]
disabled=true

[julia]
disabled=true

[kotlin]
disabled=true

[kubernetes]
disabled=true

[line_break]
disabled=false

[lua]
disabled=true

[memory_usage]
disabled=true

[nim]
disabled=true

[nix_shell]
disabled=true

[nodejs]
disabled=true

[ocaml]
disabled=true

[openstack]
disabled=true

[package]
disabled=true

[perl]
disabled=true

[php]
disabled=true

[pulumi]
disabled=true

[purescript]
disabled=true

[python]
disabled=true

[rlang]
disabled=true

[red]
disabled=true

[ruby]
disabled=true

[rust]
disabled=true

[scala]
disabled=true

[shell]
disabled=true

[shlvl]
disabled=true

[singularity]
disabled=true

[status]
disabled=true

[swift]
disabled=true

[terraform]
disabled=true

[time]
disabled=true

[username]
disabled=true

[vagrant]
disabled=true

[vlang]
disabled=true

[vcsh]
disabled=true

[zig]
disabled=true
