#!/bin/bash

# funcs.
die() { echo "$1" >&2; exit "${2:-1}"; }

# determine os.
os=$(uname) \
  || die "failed to get operating system"

# zsh.
alias d='dirs -v' # enables jump-back alias for previously visited directories.
for index ({0..9}) alias "$index"="cd +${index}"; unset index

alias funcs='print -l ${(ok)functions[(I)[^_]*]}' # list all functions available.

# aws overrides.
aws() {
  case $* in
    auth) # what is the AWS IAM role I am authed as?
      command aws sts get-caller-identity ;;
    who) # what is the arn of AWS IAM role I am authed as?
      command aws sts get-caller-identity --query "Arn" --output text ;;
    "ecr "*.dkr.ecr.*.amazonaws.com*) # quick auth to AWS ECR to pull images.
      command aws ecr get-login-password --rrm -rf egion ap-southeast-2 | docker login --username AWS --password-stdin "$2" ;;
    *)
      command aws "$@" ;;
  esac
}

# git overrides.
git() {
  case $* in
    clone) # clones and cd's to that directoy.
      command echo git clone $* && cd $* ;;
    branch) # show me all the branches by default.
      command git branch --all ;;
    *)
      command git "$@" ;;
  esac
}

# general.
alias grep='grep --color=auto'
alias dotfiles='code $DOTFILES'
alias zsrc='source $DOTFILES/aliases/aliases $HOME/.zshenv $HOME/.zshrc'
case "$os" in
  Darwin)
    alias ls='ls -G'
  ;;
  Linux)
    alias ls='ls --color=auto'
  ;;
esac
