# https://starship.rs/config

add_newline = false

[character]
success_symbol = "[->](green)"
error_symbol = "[-X](red)"

[cmd_duration]
min_time = 1_000

[directory]
truncation_symbol = ""
home_symbol = "~"
format = "[$path]($style)[$read_only]($read_only_style) "

# Explicitly disable modules that are on by default but unwanted.
[battery]
disabled = true

[aws]
disabled = true

[gcloud]
disabled = true

[kubernetes]
disabled = true

[git_state]
disabled = true

[git_metrics]
disabled = true

[hostname]
disabled = true

[username]
disabled = true

[time]
disabled = true

[jobs]
disabled = true

[status]
disabled = true

[shlvl]
disabled = true

[shell]
disabled = true

[memory_usage]
disabled = true

[env_var]
disabled = true
